name: Call snyk-workflow-master

on: workflow_dispatch

jobs:
  Find-snyk-master-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Set repository owner as environment variable
        run: echo "GITHUB_OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV

  Call-snyk-master-workflow:
    uses: ${{ env.GITHUB_OWNER }}/snyk-workflow-master/.github/workflows/snyk-workflow-master.yml@main
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
