name: Call snyk-workflow-master

on: workflow_dispatch


jobs:
    print-name:
        runs-on: ubuntu-latest
        steps:
            - name: print-name
              run: |
                  echo "${{ github.repository_owner }}"
                  
