name: Call snyk-workflow-master

on: workflow_dispatch

jobs:
  Call-snyk-master-workflow:
    uses: ${{ github.repository_owner }}/snyk-workflow-master/.github/workflows/snyk-workflow-master.yml@main

    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

