name: Snyk Container Monitor with Component Tag

on:
  push:
    branches:
      - master

jobs:

  snyk-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Snyk
        run: |
            npm install -g snyk  
            snyk auth $SNYK_TOKEN

      - name: Build docker image for juice-shop 
        run: |
            docker build -t juice-shop:1.0 .

      - name: Run Snyk Test for All Projects (Open Source)
        run: |
            snyk container monitor juice-shop:1.0 --org=cgibbs-team-d --tags="component=pkg:${{ github.repository }}@${{ github.ref_name }}"

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
